### ISSUE TITLE
GFX803

### ISSUE THREAD

**Issue by Jakub-S-K** [YellowRoseCx/koboldcpp-rocm#104]
Hello all,

There seems to be compilation error occurring from

```
commit a743d76a01f23038b2c85af1e9048ee836767b44
Author: Johannes Gäßler <johannesg@5d6.de>
Date:   Thu May 9 14:32:02 2024 +0200

    CUDA: generalize FP16 fattn vec kernel (#7061)
    
    * CUDA: generalize FP16 fattn vec kernel
    
    * disable unsupported head sizes for AMD in test
    
    * try AMD fix
    
    * fix batch size 2-8
    
    * partially revert changes

 ggml-cuda/common.cuh       | 232 ++++++++++++++++++----------------
 ggml-cuda/fattn.cu         | 305 +++++++++++++++++++++++++++++++++------------
 llama.cpp                  |   7 --
 tests/test-backend-ops.cpp |   4 +
 4 files changed, 351 insertions(+), 197 deletions(-)
```

onward

Error:
```
In file included from ggml/src/ggml-cuda/ggml-cuda.cu:7:
ggml/src/ggml-cuda/common.cuh:257:12: error: use of undeclared identifier '__hmax'; did you mean '__fmax'?
    return __hmax(a, b);
           ^~~~~~
           __fmax
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:333:1: note: '__fmax' declared here
__MATHCALLX (fmax,, (_Mdouble_ __x, _Mdouble_ __y), (__const__));
^
```

I didn't updated koboldcpp in a while (year ago) and today while updating I came across that __hmax undeclared identifier error. After quick git bisect it seems that error appears from listed changes in ggml-cuda/common.cuh

**Additional Information:**
Os: Arch Linux
CPU: Ryzen 5 2600
GPU: RX 580 8GB
ROCM: 5.4.3
KoboldCpp Version: issue is occuring from a743d76a01f23038b2c85af1e9048ee836767b44 as checked with git bisect

I koboldcpp build info: 
```
I UNAME_S:  Linux
I UNAME_P:  x86_64
I UNAME_M:  x86_64
I UNAME_O:  GNU/Linux
I CFLAGS:   -I. -Iggml/include -Iggml/src -Iggml/src/ggml-cpu -Iinclude -Isrc -I./include -I./include/CL -I./otherarch -I./otherarch/tools -I./otherarch/sdcpp -I./otherarch/sdcpp/thirdparty -I./include/vulkan -O3 -fno-finite-math-only -std=c11 -fPIC -DLOG_DISABLE_LOGS -D_GNU_SOURCE -DGGML_USE_CPU -DGGML_USE_CPU_AARCH64 -DNDEBUG -s -DGGML_USE_LLAMAFILE -pthread -Wno-deprecated -Wno-deprecated-declarations -Wno-unused-variable -pthread -march=native -mtune=native
I CXXFLAGS: -I. -Iggml/include -Iggml/src -Iggml/src/ggml-cpu -Iinclude -Isrc -I./common -I./include -I./include/CL -I./otherarch -I./otherarch/tools -I./otherarch/sdcpp -I./otherarch/sdcpp/thirdparty -I./include/vulkan -O3 -fno-finite-math-only -std=c++17 -fPIC -DLOG_DISABLE_LOGS -D_GNU_SOURCE -DGGML_USE_CPU -DGGML_USE_CPU_AARCH64 -DNDEBUG -s -DGGML_USE_LLAMAFILE -pthread -Wno-multichar -Wno-write-strings -Wno-deprecated -Wno-deprecated-declarations -Wno-unused-variable -pthread
I LDFLAGS:  -ldl
I CC:       cc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
I CXX:      g++ (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
I HIP CC:       AMD clang version 15.0.0 (https://github.com/RadeonOpenCompute/llvm-project roc-5.4.3 23045 a29fe425c7b0e5aba97ed2f95f61fd5ecba68aed)
I HIP CXX:      AMD clang version 15.0.0 (https://github.com/RadeonOpenCompute/llvm-project roc-5.4.3 23045 a29fe425c7b0e5aba97ed2f95f61fd5ecba68aed)
```
